### ISSUE TITLE
cgroup-bin required for vagrant-lxc

### ISSUE THREAD

**Issue by M1r1k** [cibox/cibox#142]
Problem (It was detected on Ubuntu 14.04 + vagrant-lxc plugin):

``` sh
There was an error executing ["sudo", "/home/[YOUR_NAME]/.vagrant.d/gems/gems/vagrant
-lxc-1.1.0/scripts/pipework", "lxcbr0", "tickalert_default_[HASH]", "
[VAGRANT_IP_ADDR]/24"]
```

Solution:

``` sh
apt-get install cgroup-bin
```

Please add this package to the list of mandatory in the description of the installation

**Comment by stucki** [comment]
I don't think this is needed. Which command from cgroup-bin does your vagrant-lxc plugin use? I see none of them:
```
dpkg -L cgroup-bin | while read FILENAME; do test -f $FILENAME || continue; git grep $(basename $FILENAME); done
```
