### ISSUE TITLE
Quickstart Guide

### ISSUE THREAD

**Issue by andreyks** [cibox/cibox#469]
Please add to Quickstart Guide next info:

1) according  Ubuntu 14.04 powered virtual machine:
 -- activate root account for external login (http://askubuntu.com/questions/469143/how-to-enable-ssh-root-access-on-ubuntu-14-04)
-- setup without password login (http://www.thegeekstuff.com/2008/11/3-steps-to-perform-ssh-login-without-password-using-ssh-keygen-ssh-copy-id/_

2) add note that ansible 1.9.x is required

**Comment by Sanchiz** [comment]
@andreyks please add this into https://github.com/cibox/cibox/blob/master/docs/Quickstart.md and Pull Request.
