### ISSUE TITLE
repository.sh fails with rsync error

### ISSUE THREAD

**Issue by danylevskyi** [cibox/cibox#499]
Command: `sh repository.sh`

```
ASK [../core/cibox-project-builder : Copy files to project directory] *********
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/tmp/drupal_latest/drupal-8.2.0-beta2/\" \"/home/dmytro/Projects/the_project/services/repo/docroot\"", "failed": true, "msg": "rsync: mkdir \"/home/dmytro/Projects/the_project/services/repo/docroot\" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]\n", "rc": 11}
```

**Comment by vasilyyaremchuk** [comment]
I have got 

fatal: [127.0.0.1]: FAILED! => {"changed": false, "dest": "/tmp/drupal_latest", "failed": true, "gid": 0, "group": "wheel", "handler": "TgzArchive", "mode": "0755", "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/drupal_latest/drupal-7.50/'", "owner": "root", "size": 68, "src": "/tmp/drupal_latest.tar.gz", "state": "directory", "uid": 0}

when I did

./repository.sh

is this the same issue?

**Comment by danylevskyi** [comment]
Ansible 2.* is not supported yet...
