### ISSUE TITLE
Failing provision the cibox because of conflict php7 and xhprof

### ISSUE THREAD

**Issue by ddrozdik** [cibox/cibox#547]
The last version of cibox is not working due to fail of compiling xhprof. 
Xhprof is not working with PHP 7. 
See for details: https://github.com/phacility/xhprof/issues/73 and https://secure.phabricator.com/T9805

**Comment by podarok** [comment]
We can disable xhprof because it is used rarely

**Comment by duozersk** [comment]
Agreed, xdebug has profiler too. We don't really need 2 tools, do we?
