### ISSUE TITLE
Task "Download Drupal to temporary directory" does not work

### ISSUE THREAD

**Issue by ddrozdik** [cibox/cibox#563]
Changes added to this line https://github.com/cibox/cibox/blob/master/core/cibox-project-builder/tasks/drupal.yml#L20 does not work on Mac OS X with grep 2.5.1-FreeBSD. 

**drupal_release** variable does not have a value after executing previous task "Extract current release"

cc @Sanchiz , @podarok

**Comment by podarok** [comment]
@ddrozdik heh
Not that easy to test, I'll try to use some docker of FreeBSD to test scripts
Is it possible to use Ubuntu container for running project builder til then?
