### ISSUE TITLE
NFS on Windows

### ISSUE THREAD

**Issue by fat763** [cibox/cibox#575]
As per Vagrant [documentation](https://www.vagrantup.com/docs/synced-folders/nfs.html): 

> Windows users: NFS folders do not work on Windows hosts. Vagrant will ignore your request for NFS synced folders on Windows.

It's true and CiBox on Windows hosts is not so fast as it might be. But i found this vagrant plugin that enables NFS support on Windows hosts: https://github.com/winnfsd/vagrant-winnfsd 

I've Installed it, works good, based on my feeling project started to work much more faster than it was. 

Would you kindly to provide some information how to measure difference between `NFS` and `no NFS` on windows hosts? If there is really big difference between performance on windows i would like to see this plugin loaded as dependency to Cibox on Windows.

**Comment by podarok** [comment]
@fat763 
I would suggest to measure in a simple way - copying a folder of files

```
vagrant up (with non NFS version) & vagrant ssh
cd /var/www
time cp -rv docroot docroot.test
```

```
vagrant up (with NFS version) && vagrant ssh
cd /var/www
time cp -rv docroot docroot.test
```

and compare output from the time commands

**Comment by fat763** [comment]
Thanks, @podarok 

Looks like it's not so fast as i thought, -50% of file system performance comparing with default files sync method:

## Windows 10 + VirtualBox (default sync method): 
```
# time cp -r /var/www/docroot /var/www/docroot.test; rm -rf /var/www/docroot.test
real    4m51.573s
user    0m0.043s
sys     0m28.149s

# dd if=/dev/zero of=/var/www/speedtest.test conv=fdatasync bs=64k count=10k; rm -f /var/www/speedtest.test
10240+0 records in
10240+0 records out
671088640 bytes (671 MB) copied, 1.57632 s, 426 MB/s
```

## Windows 10 + VirtualBox + NFS:
```
# time cp -r /var/www/docroot /var/www/docroot.test; rm -rf /var/www/docroot.test
real    5m8.989s
user    0m0.089s
sys     0m10.701s

# dd if=/dev/zero of=/var/www/speedtest.test conv=fdatasync bs=64k count=10k; rm -f /var/www/speedtest.test
10240+0 records in
10240+0 records out
671088640 bytes (671 MB) copied, 4.24518 s, 158 MB/s
```

Even slower than default, but visually faster. Anyway It's hard to deny benchmarks. Closing issue as not needed.

**Comment by podarok** [comment]
great to get real test results
as Best Practice in case if I need to work with huge amount of files I'm used to manipulate on host machine, not within VM
