### ISSUE TITLE
This site can’t be reached occasional error.

### ISSUE THREAD

**Issue by alexandar87** [cibox/cibox#576]
As i developer using Mac im getting occasional problems opening a website. 

It usually happens around 2 times per hour, and i need to refresh page until it starts working again. Downtime lasts anywhere between 1min and 10min. 

Is anyone else experiencing same issues, is there any solution?

First i thought it happens when i do **drush cr** but its not actually correct, i did not found exact trigger for that yet.

![screen shot 2017-04-26 at 13 14 06](https://cloud.githubusercontent.com/assets/3238879/25433080/71c8a490-2a87-11e7-8053-5cb3e2b35cec.png)

Thanks
Alex

**Comment by duozersk** [comment]
Adding the entry into the /etc/hosts on Mac should help here:
192.168.56.132 drupal.192.168.56.132.xip.io

Please try it out and report back.

**Comment by alexandar87** [comment]
I did added that record on my hosts file and so far ( 2 working days ) i did not get that error anymore. 

I would say that this fixed it. Is it possible to include this in installation steps or, even better, make it automatically add the necessary settings?

**Comment by podarok** [comment]
@alexandar87 every project has its own README.md where this issue is dfescribed

**Comment by alexandar87** [comment]
@podarok Yep i can see it, thanks for pointing me to it.
