### ISSUE TITLE
Script cannot obtain latest Drupal version

### ISSUE THREAD

**Issue by Sanchiz** [cibox/cibox#581]
When you generate new project, Ansible script cannot obrain Drupal version from XML.

**Comment by ddrozdik** [comment]
this happens only on Mac Os X

**Comment by ddrozdik** [comment]
actually, I have already reported this issue here https://github.com/cibox/cibox/issues/563

**Comment by podarok** [comment]
Duplicate of https://github.com/cibox/cibox/issues/563
